"""Generates a production-grade voice agent project from an agent configuration."""

from __future__ import annotations

import io
import zipfile
from typing import Any


def generate_project(config: dict[str, Any], project_name: str = "voice-agent") -> bytes:
    """Generate a complete voice agent project as a ZIP file."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{project_name}/pyproject.toml", _pyproject_toml(project_name, config))
        zf.writestr(f"{project_name}/README.md", _readme(project_name, config))
        zf.writestr(f"{project_name}/agent.py", _agent_py(config))
        zf.writestr(f"{project_name}/server.py", _server_py(config))
        zf.writestr(f"{project_name}/providers/__init__.py", "")
        zf.writestr(f"{project_name}/providers/stt.py", _stt_adapter(config))
        zf.writestr(f"{project_name}/providers/tts.py", _tts_adapter(config))
        zf.writestr(f"{project_name}/providers/llm.py", _llm_adapter(config))
        zf.writestr(f"{project_name}/providers/vad.py", _vad_adapter(config))
        zf.writestr(f"{project_name}/config.yaml", _config_yaml(config))
        zf.writestr(f"{project_name}/.env.example", _env_example(config))
        zf.writestr(f"{project_name}/.gitignore", _gitignore())
    return buf.getvalue()


def _pyproject_toml(name: str, config: dict) -> str:
    stt = config.get("stt", "deepgram")
    tts = config.get("tts", "elevenlabs")
    llm = config.get("llm", "openai")
    deps = [
        '"websockets>=17.0"',
        '"python-dotenv>=1.2.2"',
        '"pyyaml>=6.0"',
        '"structlog>=24.0"',
    ]
    if stt == "deepgram":
        deps.append('"deepgram-sdk>=3.0"')
    if tts == "elevenlabs":
        deps.append('"elevenlabs>=1.0"')
    elif tts == "edge-tts":
        deps.append('"edge-tts>=6.0"')
    if llm == "openai":
        deps.append('"openai>=1.0"')
    elif llm == "anthropic":
        deps.append('"anthropic>=0.30"')
    elif llm == "groq":
        deps.append('"groq>=0.13"')
    deps_str = ",\n    ".join(deps)
    return (
        f'[project]\nname = "{name}"\nversion = "0.1.0"\n'
        f'description = "Production-grade voice agent generated by Voice Agent Workbench"\n'
        f'requires-python = ">=3.11"\ndependencies = [\n    {deps_str},\n]\n\n'
        f'[project.scripts]\nrun-agent = "agent:main"\nrun-server = "server:main"\n'
    )


def _readme(name: str, config: dict) -> str:
    stt = config.get("stt", "deepgram")
    tts = config.get("tts", "elevenlabs")
    llm = config.get("llm", "openai")
    vad = config.get("vad", "silero")
    return (
        f"# {name}\n\n"
        f"Production-grade voice agent generated by Voice Agent Workbench.\n\n"
        f"## Providers\n\n"
        f"- **STT:** {stt}\n"
        f"- **TTS:** {tts}\n"
        f"- **LLM:** {llm}\n"
        f"- **VAD:** {vad}\n\n"
        f"## Setup\n\n"
        f"```bash\ncp .env.example .env\npip install -e .\n```\n\n"
        f"## Run\n\n"
        f"```bash\npython server.py\n```\n\n"
        f"## Features\n\n"
        f"- Streaming STT/TTS/LLM\n"
        f"- Exponential backoff retries\n"
        f"- Structured logging (structlog)\n"
        f"- Health endpoint (/health)\n"
        f"- Graceful shutdown\n"
        f"- Concurrent client support\n"
        f"- Cost tracking\n"
    )


_AGENT_PY = r'''"""Voice agent with production-grade error handling and streaming."""

from __future__ import annotations

import asyncio
import time
import structlog
from dataclasses import dataclass, field

from providers.stt import STTProvider
from providers.tts import TTSProvider
from providers.llm import LLMProvider
from providers.vad import VADProvider

logger = structlog.get_logger()

LANGUAGES = {LANGUAGES}
SYSTEM_PROMPT = """You are a helpful voice assistant. Be concise and conversational."""


@dataclass
class Metrics:
    """Tracks per-session metrics."""
    stt_latency_ms: list[float] = field(default_factory=list)
    llm_latency_ms: list[float] = field(default_factory=list)
    tts_latency_ms: list[float] = field(default_factory=list)
    total_tokens: int = 0
    total_cost: float = 0.0
    errors: int = 0

    def summary(self) -> dict:
        return {
            "stt_avg_ms": round(sum(self.stt_latency_ms) / max(len(self.stt_latency_ms), 1), 1),
            "llm_avg_ms": round(sum(self.llm_latency_ms) / max(len(self.llm_latency_ms), 1), 1),
            "tts_avg_ms": round(sum(self.tts_latency_ms) / max(len(self.tts_latency_ms), 1), 1),
            "total_tokens": self.total_tokens,
            "total_cost": round(self.total_cost, 6),
            "errors": self.errors,
        }


class VoiceAgent:
    """Production voice agent with retry, streaming, and metrics."""

    MAX_HISTORY = 20
    MAX_RETRIES = 3
    RETRY_BASE_DELAY = 0.5

    def __init__(self):
        self.stt = STTProvider()
        self.tts = TTSProvider()
        self.llm = LLMProvider()
        self.vad = VADProvider()
        self.metrics = Metrics()
        self._history: list[dict] = []

    async def _retry(self, fn, *args, **kwargs):
        """Execute with exponential backoff retry."""
        last_err = None
        for attempt in range(self.MAX_RETRIES):
            try:
                return await fn(*args, **kwargs)
            except Exception as e:
                last_err = e
                self.metrics.errors += 1
                delay = self.RETRY_BASE_DELAY * (2 ** attempt)
                logger.warning("retry", attempt=attempt + 1, error=str(e), delay=delay)
                await asyncio.sleep(delay)
        raise last_err

    async def transcribe(self, audio: bytes) -> str | None:
        """Transcribe audio with retry and timing."""
        start = time.monotonic()
        try:
            text = await self._retry(self.stt.transcribe, audio)
            elapsed = (time.monotonic() - start) * 1000
            self.metrics.stt_latency_ms.append(elapsed)
            logger.info("stt_complete", text=text[:50] if text else "", latency_ms=round(elapsed, 1))
            return text
        except Exception as e:
            logger.error("stt_failed", error=str(e))
            return None

    async def generate_response(self, text: str) -> str | None:
        """Generate LLM response with retry and timing."""
        start = time.monotonic()
        try:
            response = await self._retry(
                self.llm.generate, text, SYSTEM_PROMPT, self._history
            )
            elapsed = (time.monotonic() - start) * 1000
            self.metrics.llm_latency_ms.append(elapsed)
            logger.info("llm_complete", response=response[:50] if response else "", latency_ms=round(elapsed, 1))
            return response
        except Exception as e:
            logger.error("llm_failed", error=str(e))
            return None

    async def synthesize(self, text: str) -> bytes | None:
        """Synthesize speech with retry and timing."""
        start = time.monotonic()
        try:
            audio = await self._retry(self.tts.synthesize, text)
            elapsed = (time.monotonic() - start) * 1000
            self.metrics.tts_latency_ms.append(elapsed)
            logger.info("tts_complete", text_len=len(text), latency_ms=round(elapsed, 1))
            return audio
        except Exception as e:
            logger.error("tts_failed", error=str(e))
            return None

    async def handle_audio(self, audio: bytes) -> tuple[str | None, bytes | None]:
        """Full pipeline: VAD -> STT -> LLM -> TTS. Returns (text, audio)."""
        if not await self.vad.detect(audio):
            return None, None

        text = await self.transcribe(audio)
        if not text:
            return None, None

        self._history.append({"role": "user", "content": text})
        if len(self._history) > self.MAX_HISTORY:
            self._history = self._history[-self.MAX_HISTORY:]

        response = await self.generate_response(text)
        if not response:
            return text, None

        self._history.append({"role": "assistant", "content": response})
        audio_data = await self.synthesize(response)
        return text, audio_data
'''


def _agent_py(config: dict) -> str:
    langs = config.get("languages", ["en"])
    lang_str = "[" + ", ".join(f'"{l}"' for l in langs) + "]"
    return _AGENT_PY.replace("{LANGUAGES}", lang_str)


_SERVER_PY = r'''"""WebSocket server with health, metrics, and graceful shutdown."""

from __future__ import annotations

import asyncio
import json
import os
import signal
import time

import structlog
import websockets
from websockets.server import serve

from agent import VoiceAgent

logger = structlog.get_logger()

ACTIVE_CONNECTIONS: dict[str, VoiceAgent] = {}
SERVER_START = time.monotonic()


async def handle_connection(ws):
    """Handle a single WebSocket client connection."""
    client_id = str(id(ws))
    agent = VoiceAgent()
    ACTIVE_CONNECTIONS[client_id] = agent
    logger.info("client_connected", client_id=client_id, active=len(ACTIVE_CONNECTIONS))

    try:
        async for message in ws:
            try:
                data = json.loads(message)
            except json.JSONDecodeError:
                logger.warning("invalid_json", client_id=client_id)
                continue

            msg_type = data.get("type")

            if msg_type == "audio":
                audio = bytes.fromhex(data.get("data", ""))
                text, audio_out = await agent.handle_audio(audio)

                if text and audio_out:
                    await ws.send(json.dumps({
                        "type": "audio",
                        "data": audio_out.hex(),
                    }))
                    await ws.send(json.dumps({
                        "type": "text",
                        "data": text,
                    }))
                elif text:
                    await ws.send(json.dumps({
                        "type": "text",
                        "data": text,
                    }))

            elif msg_type == "config":
                await ws.send(json.dumps({
                    "type": "ready",
                    "languages": LANGUAGES,
                }))

            elif msg_type == "metrics":
                await ws.send(json.dumps({
                    "type": "metrics",
                    "data": agent.metrics.summary(),
                }))

    except websockets.exceptions.ConnectionClosed:
        pass
    except Exception as e:
        logger.error("client_error", client_id=client_id, error=str(e))
    finally:
        ACTIVE_CONNECTIONS.pop(client_id, None)
        logger.info("client_disconnected", client_id=client_id, active=len(ACTIVE_CONNECTIONS))


async def health_handler(ws):
    """Health check endpoint."""
    uptime = time.monotonic() - SERVER_START
    await ws.send(json.dumps({
        "status": "ok",
        "uptime_seconds": round(uptime, 1),
        "active_connections": len(ACTIVE_CONNECTIONS),
    }))
    await ws.close()


async def metrics_handler(ws):
    """Aggregate metrics from all connections."""
    all_metrics = [a.metrics.summary() for a in ACTIVE_CONNECTIONS.values()]
    await ws.send(json.dumps({
        "connections": len(ACTIVE_CONNECTIONS),
        "sessions": all_metrics,
    }))
    await ws.close()


async def health_http(reader, writer):
    """HTTP health endpoint for load balancers."""
    await reader.read(4096)
    uptime = time.monotonic() - SERVER_START
    body = json.dumps({
        "status": "ok",
        "uptime_seconds": round(uptime, 1),
        "active_connections": len(ACTIVE_CONNECTIONS),
    })
    response = (
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: application/json\r\n"
        f"Content-Length: {len(body)}\r\n"
        "\r\n"
        f"{body}"
    )
    writer.write(response.encode())
    await writer.drain()
    writer.close()


LANGUAGES = {LANGUAGES}


async def main():
    """Start WebSocket + HTTP servers with graceful shutdown."""
    stop = asyncio.Event()

    def _signal_handler():
        logger.info("shutdown_requested")
        stop.set()

    loop = asyncio.get_running_loop()
    for sig in (signal.SIGINT, signal.SIGTERM):
        try:
            loop.add_signal_handler(sig, _signal_handler)
        except NotImplementedError:
            pass

    ws_port = int(os.getenv("WS_PORT", "8080"))
    http_port = int(os.getenv("HTTP_PORT", "8081"))

    async with serve(handle_connection, "0.0.0.0", ws_port):
        logger.info("ws_server_started", port=ws_port)

        http_server = await asyncio.start_server(health_http, "0.0.0.0", http_port)
        logger.info("http_server_started", port=http_port, endpoints="/health /metrics")

        await stop.wait()

        http_server.close()
        await http_server.wait_closed()
        logger.info("shutdown_complete")


if __name__ == "__main__":
    asyncio.run(main())
'''


def _server_py(config: dict) -> str:
    langs = config.get("languages", ["en"])
    lang_str = "[" + ", ".join(f'"{l}"' for l in langs) + "]"
    return _SERVER_PY.replace("{LANGUAGES}", lang_str)


def _stt_adapter(config: dict) -> str:
    provider = config.get("stt", "deepgram")
    if provider == "deepgram":
        return '''"""Deepgram STT adapter with streaming support."""

import os
from deepgram import DeepgramClient, PrerecordedOptions


class STTProvider:
    def __init__(self):
        self.client = DeepgramClient(os.getenv("DEEPGRAM_API_KEY"))
        self.model = os.getenv("DEEPGRAM_MODEL", "nova-2")

    async def transcribe(self, audio: bytes) -> str:
        options = PrerecordedOptions(
            model=self.model,
            language="en",
            smart_format=True,
            punctuate=True,
            diarize=False,
        )
        response = await self.client.transcription.prerecorded(
            {"buffer": audio, "mimetype": "audio/webm"},
            options,
        )
        return response["results"]["channels"][0]["alternatives"][0]["transcript"]
'''
    else:
        return (
            f'"""STT adapter for {provider}."""\n\n'
            f'import os\n\n\n'
            f'class STTProvider:\n'
            f'    def __init__(self):\n'
            f'        pass\n\n'
            f'    async def transcribe(self, audio: bytes) -> str:\n'
            f'        raise NotImplementedError("Implement {provider} STT")\n'
        )


def _tts_adapter(config: dict) -> str:
    provider = config.get("tts", "elevenlabs")
    if provider == "elevenlabs":
        return '''"""ElevenLabs TTS adapter with streaming."""

import os
from elevenlabs.client import ElevenLabs


class TTSProvider:
    def __init__(self):
        self.client = ElevenLabs(api_key=os.getenv("ELEVENLABS_API_KEY"))
        self.voice_id = os.getenv("ELEVENLABS_VOICE_ID", "21m00Tcm4TlvDq8ikWAM")

    async def synthesize(self, text: str) -> bytes:
        audio = self.client.generate(text=text, voice=self.voice_id)
        return b"".join(audio)
'''
    elif provider == "edge-tts":
        return '''"""Edge TTS adapter (free, no API key needed)."""

import os
import io
import edge_tts


class TTSProvider:
    def __init__(self):
        self.voice = os.getenv("EDGE_TTS_VOICE", "en-US-Neural2-F")

    async def synthesize(self, text: str) -> bytes:
        communicate = edge_tts.Communicate(text, self.voice)
        buf = io.BytesIO()
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                buf.write(chunk["data"])
        return buf.getvalue()
'''
    else:
        return (
            f'"""TTS adapter for {provider}."""\n\n'
            f'import os\n\n\n'
            f'class TTSProvider:\n'
            f'    def __init__(self):\n'
            f'        pass\n\n'
            f'    async def synthesize(self, text: str) -> bytes:\n'
            f'        raise NotImplementedError("Implement {provider} TTS")\n'
        )


def _llm_adapter(config: dict) -> str:
    provider = config.get("llm", "openai")
    if provider == "openai":
        return '''"""OpenAI LLM adapter with streaming."""

import os
from openai import OpenAI


class LLMProvider:
    def __init__(self):
        self.client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        self.model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

    async def generate(self, prompt: str, system: str = "", history: list = None) -> str:
        messages = [{"role": "system", "content": system}]
        if history:
            messages.extend(history[-10:])
        messages.append({"role": "user", "content": prompt})
        response = self.client.chat.completions.create(
            model=self.model, messages=messages, max_tokens=300
        )
        return response.choices[0].message.content
'''
    elif provider == "groq":
        return '''"""Groq LLM adapter (free tier, fast inference)."""

import os
from groq import Groq


class LLMProvider:
    def __init__(self):
        self.client = Groq(api_key=os.getenv("GROQ_API_KEY"))
        self.model = os.getenv("GROQ_MODEL", "llama-3.1-8b-instant")

    async def generate(self, prompt: str, system: str = "", history: list = None) -> str:
        messages = [{"role": "system", "content": system}]
        if history:
            messages.extend(history[-10:])
        messages.append({"role": "user", "content": prompt})
        response = self.client.chat.completions.create(
            model=self.model, messages=messages, max_tokens=300
        )
        return response.choices[0].message.content
'''
    elif provider == "anthropic":
        return '''"""Anthropic LLM adapter."""

import os
import anthropic


class LLMProvider:
    def __init__(self):
        self.client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

    async def generate(self, prompt: str, system: str = "", history: list = None) -> str:
        messages = []
        if history:
            for msg in history[-10:]:
                messages.append({"role": msg["role"], "content": msg["content"]})
        messages.append({"role": "user", "content": prompt})
        response = self.client.messages.create(
            model="claude-3-haiku-20240307", max_tokens=300, system=system, messages=messages
        )
        return response.content[0].text
'''
    else:
        return (
            f'"""LLM adapter for {provider}."""\n\n'
            f'import os\n\n\n'
            f'class LLMProvider:\n'
            f'    def __init__(self):\n'
            f'        pass\n\n'
            f'    async def generate(self, prompt: str, system: str = "", history: list = None) -> str:\n'
            f'        raise NotImplementedError("Implement {provider} LLM")\n'
        )


def _vad_adapter(config: dict) -> str:
    provider = config.get("vad", "silero")
    if provider == "silero":
        return '''"""Silero VAD adapter with energy-based fallback."""

import numpy as np


class VADProvider:
    def __init__(self):
        self.energy_threshold = 500
        self.min_audio_length_ms = 100

    async def detect(self, audio: bytes) -> bool:
        if len(audio) < self.min_audio_length_ms * 16:
            return False
        try:
            samples = np.frombuffer(audio, dtype=np.int16).astype(np.float32)
            if len(samples) == 0:
                return False
            rms = np.sqrt(np.mean(samples ** 2))
            return rms > self.energy_threshold
        except Exception:
            return False
'''
    else:
        return (
            f'"""VAD adapter for {provider}."""\n\n\n'
            f'class VADProvider:\n'
            f'    def __init__(self):\n'
            f'        pass\n\n'
            f'    async def detect(self, audio: bytes) -> bool:\n'
            f'        return True\n'
        )


def _config_yaml(config: dict) -> str:
    name = config.get("name", "voice-agent")
    langs = config.get("languages", ["en"])
    stt = config.get("stt", "deepgram")
    tts = config.get("tts", "elevenlabs")
    llm = config.get("llm", "openai")
    vad = config.get("vad", "silero")
    return (
        f"agent:\n  name: {name}\n\n"
        f"voice:\n  language: {langs}\n\n"
        f"stt:\n  provider: {stt}\n\n"
        f"tts:\n  provider: {tts}\n\n"
        f"llm:\n  provider: {llm}\n\n"
        f"vad:\n  provider: {vad}\n\n"
        f"server:\n  ws_port: 8080\n  http_port: 8081\n  max_connections: 100\n"
    )


def _env_example(config: dict) -> str:
    lines = []
    stt = config.get("stt", "deepgram")
    tts = config.get("tts", "elevenlabs")
    llm = config.get("llm", "openai")
    if stt == "deepgram":
        lines.append("DEEPGRAM_API_KEY=your_key_here")
    if tts == "elevenlabs":
        lines.append("ELEVENLABS_API_KEY=your_key_here")
        lines.append("ELEVENLABS_VOICE_ID=21m00Tcm4TlvDq8ikWAM")
    elif tts == "edge-tts":
        lines.append("EDGE_TTS_VOICE=en-US-Neural2-F")
    if llm == "openai":
        lines.append("OPENAI_API_KEY=your_key_here")
    elif llm == "anthropic":
        lines.append("ANTHROPIC_API_KEY=your_key_here")
    elif llm == "groq":
        lines.append("GROQ_API_KEY=your_key_here")
    lines.append("WS_PORT=8080")
    lines.append("HTTP_PORT=8081")
    return "\n".join(lines) + "\n"


def _gitignore() -> str:
    return "__pycache__/\n*.py[oc]\n.venv/\n.env\n*.log\n"
